sudo: true

language: python

python:
  - "2.7"

services:
    - mysql
addons:
    apt:
        packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
env:
    DB_HOST: 127.0.0.1
    DB_PORT: 3306
    DB_USER: root
    DB_WD: root

install: "pip install -r requirements.txt"

before_script:
    #create tables
    - mysql < ./schema.sql -uroot --verbose

script:
    - source ./env.sh
    - python -m unittest discover -v -s ./tests/unit -p "test_*.py"
branches:
  only:
    - master
