language: python
python:
  - "2.7"

install: "pip install -r requirements.txt"

script:
    -source ./env.sh
    -python -m unittest discover -v -s ./tests/unit -p "test_*.py"
branches:
  only:
    - master
