sudo: true

language: python

python:
  - "2.7"

services:
    - mysql
addons:
    apt:
        packages:
            - mysql-server
            - python-pip
env:
    DB_HOST: 127.0.0.1
    DB_PORT: 3306
    DB_USER: root
    DB_WD: 

install: 
    - "pip install pip==1.5.6"
    - "pip install -r requirements.txt"

before_script:
    #create tables
    - mysql < ./schema.sql -uroot --verbose

script:
    - source ./env.sh
    - python -m unittest discover -v -s ./tests/unit -p "test_*.py"
branches:
  only:
    - master
