sudo: true

language: python

python:
  - "2.7"

services:
    - postgresql

addons:
      postgresql: "9.3"

install: 
        - "pip install tox"
env:
    DB_HOST: 127.0.0.1
    DB_PORT: 5432
    DB_USER: root
    DB_WD: root

before_script:
    #Set postgreSQL password for root user
    - psql -c "CREATE ROLE root LOGIN password 'root';" -U postgres
    - psql -c "CREATE DATABASE eagle ENCODING 'UTF8' OWNER root;" -U postgres
    #Create tables
    - PGPASSWORD=root psql -Uroot -h127.0.0.1 -p5432 -d eagle < ./schema.sql

script:
    - tox

branches:
  only:
    - master
